format = """
[](#515b68)\
$username\
[](bg:#DA627D fg:#515b68)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#6288c0)\
$nodejs\
$python\
[](fg:#6288c0 bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = true

# env variable
[env_var]
variable = "SHELL"
default = "unknown shell"

# You can also replace your username with a neat symbol like  to save some space
[username]
# user = " "
show_always = true
style_user = "bg:#515b68"
style_root = "bg:#d80000"
format = '[$user ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[[ $symbol $branch ]($style)]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[[($all_status$ahead_behind )]($style)]($style)'

[nodejs]
symbol = ""
style = "bg:#6288c0"
format = '[[ $symbol ($version) ]($style)]($style)'

[python]
# Display the version of python from inside a local venv.
#
# Note this will only work when the venv is inside the project and it will only
# work in the directory that contains the venv dir but maybe this is ok?
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
style = "bg:#6288c0"
format = '[[ $symbol $version $virtualenv ]($style)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[  $time ]($style)]($style)'
